### ISSUE TITLE
Some questions about the state of project

### ISSUE THREAD

**Issue by mcfatealan** [gpudirect/libgdsync#2]
Hi @drossetti , I'm a researcher from Shanghai Jiao Tong University. We're working on building a graph system for GPU clusters and we would like adapt GPU-initiate RDMA as the major way to transfer data between GPUs on different machines. I'm very interested in this newly announced GPUDirect Async technique. I'm wondering, is this technique ready for prototype use? If so, this would be fascinating!

If not, will there be a release version lately? No matter what, this gonna be super cool. 

Any response would be highly appreciated, thx!

**Comment by drossetti** [comment]
@mcfatealan for some reason, I noticed this message only now.
Async can be considered as being at the prototype stage.
Please have a look at the devel branch.
I am interested in any feedback.

**Comment by mtweak** [comment]
@drossetti:  I'm getting an error for missing library when trying to build the tests.  Where would I find gdstools?

$ cd build
$ ../configure --enable-test --with-mpi=/usr/lib/openmpi
(...)
$ make
make  all-am
make[1]: Entering directory '/home/mazhar/test/libgdsync/build'
  CXXLD    tests/gds_poll_lat
/usr/bin/ld: cannot find -lgdstools
collect2: error: ld returned 1 exit status
Makefile:654: recipe for target 'tests/gds_poll_lat' failed
make[1]: *** [tests/gds_poll_lat] Error 1
make[1]: Leaving directory '/home/mazhar/test/libgdsync/build'
Makefile:464: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by drossetti** [comment]
@mtweak ah right, I forgot to get rid of that. Could you please just try and remove that library locally ? I'll fix that shortly.

**Comment by drossetti** [comment]
@mtweak this problem has been fixed on the devel branch

**Comment by mcfatealan** [comment]
Hi @drossetti , thanks so much for your response! I'm sorry that I didn't see the notification because I thought my message was ignored...  
Since Async is not production available yet, we decided to make full use of current GPUDirect to achieve our goal. (Previously we may overestimate our demands for communication.) Anyway, we really appreciate your information :D 
Wish everything works well.
