### ISSUE TITLE
The member "inlineCopy" of CUstreamBatchMemOpParams

### ISSUE THREAD

**Issue by brave-hannah** [gpudirect/libgdsync#37]
I have installed CUDA 8.0, but I can't find inlineCopy from struct CUstreamBatchMemOpParams in my cuda.h. 
So, is there something else need to install or patch ? 
And what's the meaning of inlineCopy exactly?
Thanks a lot.

**Comment by drossetti** [comment]
That is related to an experimental feature which we have played with.
 That code is GDS_HAS_INLINE_COPY, so it should build correctly. What is exactly the problem?

**Comment by brave-hannah** [comment]
So, can I use this feature now with master version of the code?

**Comment by brave-hannah** [comment]
Addition, is there an improvement in performance with this feature open?

**Comment by drossetti** [comment]
no you cannot use this feature, as it relies on unreleased CUDA APIs
performance improvements would be marginal, probably only showing in simple synthetic benchmarks.

**Comment by brave-hannah** [comment]
ok, thank you very much.
