### ISSUE TITLE
Couldn't register MR when execute gds_kernel_latency

### ISSUE THREAD

**Issue by brave-hannah** [gpudirect/libgdsync#40]
With Tesla P4 and mellanox CX4, the gds_kernel_latency runs into the error "Couldn't register MR" every time on Ubuntu 14.04.4.

The output is like:

allocated GPU buffer address at 000001030b000000
ctx buf=0x1030b000000
allocated GPU buffer address at 000001030b000000
ctx buf=0x1030b000000
poisoning GPU buffer, filled with '0x00' !!!
poisoning GPU buffer, filled with '0x00' !!!
cuMemAlloc() of a 131072 bytes GPU buffer
cuMemAlloc() of a 131072 bytes GPU buffer
allocated GPU buffer address at 000001030b200000
cuMemAlloc() of a 131072 bytes GPU buffer
allocated GPU buffer address at 000001030b200000
cuMemAlloc() of a 131072 bytes GPU buffer
allocated GPU buffer address at 000001030b220000
allocated GPU buffer address at 000001030b220000
Couldn't register MR
Couldn't register MR

-------------------------------------------------------

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

-------------------------------------------------------

--------------------------------------------------------------------------

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52222,1],1]
  Exit code:    1

I've checked my NIC status but everything is ok, also the IB mode as required. So, what's wrong and how to fix this problem ?

**Comment by brave-hannah** [comment]
I guess I have found the reason of this problem, that I used the wrong cuda driver version 374.xx. Maybe you could add this limitation to the README. After updating cuda driver to 384.xx, everything is ok.

**Comment by drossetti** [comment]
@brave-hannah the README.md clearly states:
"A recent display driver, i.e. r361, r367 or later, is required."

Note that in r387 a new kernel module param has been added, see issue #41 

Most probably your problem is that you don't have nv_peer_mem loaded, so ibv_reg_mr() does not work on GPU memory.

feel free to close this issue if that was the case

**Comment by brave-hannah** [comment]
maybe, I will try later. Thank you very much.
