### ISSUE TITLE
change signature and refactor implementation of gds_post_send

### ISSUE THREAD

**Issue by e-ago** [gpudirect/libgdsync#5]
This function:

- Doesn't take the expanded version of the input data structures
- Uses the ibv_post_send() instead of ibv_exp_post_send()
- Should recall the gds_prepare_send() as the gds_stream_queue_send_ex()

It is used in files:

- libgdsync/tests/gds_kernel_latency.c
- libgdsync/tests/gds_kernel_loopback_latency.c
- libmp/src/mp.c

**Comment by drossetti** [comment]
@e-ago please close this as soon as verified
