### ISSUE TITLE
 error, stream must NOT be idle at this point

### ISSUE THREAD

**Issue by YuxinxinChen** [gpudirect/libgdsync#58]
```bash
starting test...
Performance instrumentation is disabled
[5475] GDS ERR   gds_stream_batch_ops() got CUDA result 801 (operation not supported) while submitting batch operations:
[5475] GDS ERR   gds_stream_batch_ops() nops=1 flags=00000000
[5475] GDS INFO  gds_dump_params() param[0]:
[5475] GDS INFO  gds_dump_param() WAIT32 addr:0x207000000 alias:(nil) value:00000001 flags:00000000
[5475] GDS ERR   gds_stream_post_descriptors() error in batch_ops
[5475] GDS ERR   gds_stream_batch_ops() got CUDA result 801 (operation not supported) while submitting batch operations:
[5475] GDS ERR   gds_stream_batch_ops() nops=1 flags=00000000
[5475] GDS INFO  gds_dump_params() param[0]:
[5475] GDS INFO  gds_dump_param() WRITE32 addr:0x207200000 alias:(nil) value:d4d00100 flags:00000001
[5475] GDS ERR   gds_stream_post_descriptors() error in batch_ops
ERR:  [main] error, stream must NOT be idle at this point, iter:
```
When I run ./gds_poll_lat, I got this error. 

I have started nv_peer_mem:
● nv_peer_mem.service - LSB: Activates/Deactivates nv_peer_mem to \ start at boot time.
   Loaded: loaded (/etc/init.d/nv_peer_mem; bad; vendor preset: enabled)
   Active: active (exited) since Fri 2018-04-06 19:12:19 PDT; 2 weeks 3 days ago
     Docs: man:systemd-sysv-generator(8)
softerware:
ubuntu-16.04
nvidia-driver: 390.30 
cuda-toolkit: cuda 9.1
MLNX_OFED: MLNX_LINUX_4.3
nv_peer_mem: 1.0.6

Hardware:
01:00.0 Network controller: Mellanox Technologies MT27500 Family
[ConnectX-3]
Subsystem: Mellanox Technologies MT27500 Family [ConnectX-3]
82:00.0 Network controller: Mellanox Technologies MT27500 Family
[ConnectX-3]
Subsystem: Mellanox Technologies MT27500 Family [ConnectX-3]

Tesla K40

Could anyone know how to fix this?

**Comment by drossetti** [comment]
your specific problem is on the CUDA side. have you checked the README file? there we explain the SW/HW requirements. Specifically:
options nvidia NVreg_EnableStreamMemOPs=1 NVreg_RegistryDwords="PeerMappingOverride=1"

Related, last time I checked, MLNX Peerdirect async was not support on CX-3.

**Comment by drossetti** [comment]
No I mean the APIs in peer_ops.h

**Comment by YuxinxinChen** [comment]
Hi, I have checked the Nvidia configuration: options nvidia NVreg_EnableStreamMemOPs=1 NVreg_RegistryDwords="PeerMappingOverride=1;" 

Since I am running on only one machine, I guess the MPI creates two thread to talk which may imply that it doesn't go through IB?? Is this could be the problem of CX-3? 

Also, I have check gdrcopy, for the validate and copybw, they work fine. I also notice in this README, to reload the Nvidia driver, it needs to first service gdrcopy stop? I didn't find any instruction on gdrcopy GitHub that requiring to do service gdrcopy start before using gdrcopy. Also, I didn't find gdrcopy provides some service file?

**Comment by drossetti** [comment]
gds_poll_lat is not a communication test, so you don't need MPI to run it.
It is not clear to me whether gds_poll_lat works after adding the suggested options and rebooting.
Does it work now?

Regarding your testbed, Peerdirect Async IB Verbs is only available on recent MLNX HCAs (ConnectIB or newer).
Running 2+ MPI ranks within a single server is not a problem usually, especially because libgdsync tests only use MPI as a out-of-band network, not for data exchange.

**Comment by YuxinxinChen** [comment]
Hi Davide, thank you for replying on weekend. It still doesn't work. 
The error is: gds_stream_batch_ops() got CUDA result 801

The nvidia.conf locates at the path: /etc/modprobe.d

**Comment by drossetti** [comment]
Did you reboot after tweaking the modprobe Conf file ? 
Can you check if the GPU Driver is loaded in the initramfs?
Which Linux distro?
Which kernel version ?
Which gpu driver version?
Which CUDA toolkit ?
Which GPU?
Which gpu driver installation method? Installer, deb pkg, rpm pkg,...

**Comment by haggaie** [comment]
> @ferasd @haggaie do you know if CX-3 is supported?

No, I'm afraid libmlx4 doesn't support PeerDirect Async.

**Comment by YuxinxinChen** [comment]
Hi Davide,
There is nothing in modules file at the path: /etc/initramfs-tools. 
Should I run sudo update-initramfs -u before rebooting after I change nvidia.conf?

I use:
```bash
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```
GPU driver:
```bash
Driver Version: 390.30
CUDA toolkit: cuda-9.1
```
GPU: I have 4 GPUs:
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN V             On   | 00000000:02:00.0 Off |                  N/A |
| 33%   48C    P8    28W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN V             On   | 00000000:03:00.0 Off |                  N/A |
| 38%   54C    P8    37W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN Xp            On   | 00000000:83:00.0 Off |                  N/A |
| 53%   84C    P2   125W / 250W |   8533MiB / 12196MiB |     77%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40c          On   | 00000000:84:00.0 Off |                    0 |
| 23%   44C    P8    21W / 235W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    2     17998      C   python3                                     8521MiB |
+-----------------------------------------------------------------------------+
```
But I use device 3 which is the tesla k40 by running the command with -d 3
The driver is installed via apt-get

If I buy connectX-5: http://www.mellanox.com/related-docs/prod_adapter_cards/PB_ConnectX-5_VPI_Card_SocketDirect.pdf, then we can use the peer-direct API?

**Comment by YuxinxinChen** [comment]
Hi,

I think nvidia driver is in initramfs:
```bash
yuxin420@mario:/boot$ lsinitramfs ./initrd.img-4.4.0-121-generic | grep nv
lib/modules/4.4.0-121-generic/kernel/drivers/ata/sata_nv.ko
lib/modules/4.4.0-121-generic/kernel/drivers/net/ethernet/nvidia
lib/modules/4.4.0-121-generic/kernel/drivers/net/ethernet/nvidia/forcedeth.ko
lib/modules/4.4.0-121-generic/kernel/drivers/nvme
lib/modules/4.4.0-121-generic/kernel/drivers/nvme/host
lib/modules/4.4.0-121-generic/kernel/drivers/nvme/host/nvme.ko
lib/modules/4.4.0-121-generic/updates/dkms/nvidia_390.ko
lib/modules/4.4.0-121-generic/updates/dkms/nvidia_390_modeset.ko
lib/modules/4.4.0-121-generic/updates/dkms/nvidia_390_uvm.ko
lib/modules/4.4.0-121-generic/updates/dkms/nvidia_390_drm.ko
bin/env
bin/openvt
etc/modprobe.d/nvidia-installer-disable-nouveau.conf
etc/modprobe.d/nvidia-390_hybrid.conf
etc/modprobe.d/nvidia.conf
etc/modprobe.d/nvidia-graphics-drivers.conf
```
nvidia.conf: options nvidia NVreg_EnableStreamMemOPs=1 NVreg_RegistryDwords="PeerMappingOverride=1"; is loaded.

**Comment by drossetti** [comment]
this might be your problem. the initramfs is loading the driver without the special options.

**Comment by drossetti** [comment]
closing as a local installation problem
