### ISSUE TITLE
gds_sanity and gds_poll_lat fail 

### ISSUE THREAD

**Issue by e-ago** [gpudirect/libgdsync#60]
Both `gds_sanity` and `gds_poll_lat` fail within `gds_stream_post_descriptors()` with this error:
```
GDS ERR   peer_from_stream() cannot find GPU associated to stream=0x1140c70 for which a GDS QP has been created
```

They don't create a QP (CQ) with `gds_create_qp()` (`gds_create_cq()`) so `gds_register_peer_ex()` is not called and peer is not registered.

Tested on brdw (r390.55 and cuda 9.0) and DGX (r396.14, cuda 9.2)

**Comment by e-ago** [comment]
Should we create a public peer registration function independent from gds_create_qp/gds_create_cq functions?

**Comment by drossetti** [comment]
peer_from_stream() should simply register the GPU on demand.

**Comment by drossetti** [comment]
@e-ago my commit d671068 in new_memops fixes this issue
