### ISSUE TITLE
Question: libgdsync without MPI for network communication

### ISSUE THREAD

**Issue by mi5ul** [gpudirect/libgdsync#69]
Hi,

I am developing a basic demonstration of inter-node GPU-GPU RDMA data transfer over an InfiniBand network. I would like to use libgdsync but feel that MPI adds additional weight to my application that I do not need. 

Is the use of MPI encouraged with libgdsync (or with any of the GPUDirect technologies for that matter) or can I perform network communication with the Verbs API exclusively?

Do any of the libgdsync tests provide options for inter-node benchmarks without MPI?

Thank you

**Comment by e-ago** [comment]
@mi5ul As written into the README, libmp is a lightweight messaging library built on top of libgdsync.
It uses MPI as out-of-band method to exchange initial IB info but for the actual communication you can use libmp functions only.
We created a general GPUDirect Async repository here https://github.com/gpudirect/gdasync with several scripts useful to configure, build and run libgdsync/libmp libraries, tests, benchmarks and applications.

**Comment by mi5ul** [comment]
Thank you both for the given resources, will definitely check them out. libmp does sound like something that would be suitable for my application.
